# Generated by Django 4.0.1 on 2023-05-26 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_company_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='destination_hub',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='destinaiton', to='main.hub'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='source_hub',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='source', to='main.hub'),
            preserve_default=False,
        ),
    ]
