# Generated by Django 4.0.1 on 2023-05-26 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ride_destination_hub_ride_source_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='workload',
            field=models.CharField(default='', max_length=300, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
    ]
