# Generated by Django 4.2.1 on 2023-05-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_user_points_alter_company_workload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='ride2passengers',
            options={'verbose_name': 'Ride2Passengers', 'verbose_name_plural': 'Rides2Passengers'},
        ),
        migrations.RenameField(
            model_name='ride2passengers',
            old_name='destination',
            new_name='source_hub',
        ),
    ]
