# Generated by Django 4.2.1 on 2023-05-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ride_destination_time_ride_spots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='spots',
        ),
        migrations.AddField(
            model_name='ride',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
