# Generated by Django 4.2.1 on 2023-05-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_ride_spots_ride_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='info',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
