# Generated by Django 4.2.1 on 2023-05-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_hub_info_alter_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
